GET 127.0.0.1:8000/check_username?username=aa

###

GET 127.0.0.1:8000/check_username?username=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

###

GET 127.0.0.1:8000/check_username?username=username

###

GET 127.0.0.1:8000/check_username